services:
  - type: web
    name: n8n-service
    env: docker
    image:
      url: docker.io/n8nio/n8n:latest
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: n8n-db
          property: connectionString

databases:
  - name: n8n-db
    plan: free
