services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: n8n-db
          property: connectionString
      - key: N8N_TRUST_PROXY
        value: true
      - key: N8N_WEBHOOK_URL
        value: "https://YOUR_SERVICE_NAME.onrender.com"

databases:
  - name: n8n-db
    plan: free
